#!/bin/sh
# Regenerate a target's predefined-macro table from the reference compiler.
#
# ARCHITECTURE.md §5: the predefined-macro table is taken from
# `<triple>-gcc -dM -E </dev/null`, never hand-derived. This script is the
# only way those files may change; the generated tables are checked in so
# the build (and eventual self-hosting) does not depend on the cross
# toolchain.
#
# usage: gen-predef.sh [x86_64|aarch64]     (default: both)
#
# Excluded families, each for THE RULE (claim only what is present):
#   __GNUC*__, __VERSION__   EmbCC is not gcc; defining these would switch
#                            real headers onto gcc-only extension paths.
#   __STDC*__                owned by the compiler proper, not the target;
#                            cpp defines them itself (see predef.h).
set -eu

gen() {
    arch=$1
    gccvar=$(echo "EMBCC_REF_GCC_$arch" | tr '[:lower:]' '[:upper:]')
    eval "GCC=\${$gccvar:-$arch-elf-gcc}"
    OUT="$(dirname "$0")/../src/cpp/predef_$arch.c"

    command -v "$GCC" >/dev/null 2>&1 || {
        echo "gen-predef: reference compiler '$GCC' not found" >&2
        echo "gen-predef: set $gccvar or add it to PATH" >&2
        exit 1
    }

    {
        echo "/* Generated by tools/gen-predef.sh from \`$("$GCC" -dumpmachine) gcc $("$GCC" -dumpversion) -dM -E\`."
        echo "   Do not edit by hand; rerun the script (ARCHITECTURE.md §5). */"
        echo
        echo "#include \"predef.h\""
        echo
        echo "const struct predef_macro predef_macros_$arch[] = {"
        "$GCC" -dM -E - </dev/null \
            | LC_ALL=C sort \
            | grep -v -E '^#define (__GNUC|__VERSION__|__STDC)' \
            | sed -e 's/^#define \([^ ]*\) \(.*\)$/\1\x01\2/' \
            | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' \
            | sed -e 's/^\(.*\)\x01\(.*\)$/    { "\1", "\2" },/'
        echo "};"
        echo
        echo "const int predef_macro_count_$arch ="
        echo "    (int)(sizeof predef_macros_$arch / sizeof predef_macros_$arch[0]);"
    } > "$OUT"

    echo "gen-predef: wrote $OUT ($(grep -c '{ "' "$OUT") macros)"
}

case "${1:-both}" in
    x86_64)  gen x86_64 ;;
    aarch64) gen aarch64 ;;
    both)    gen x86_64; gen aarch64 ;;
    *) echo "usage: $0 [x86_64|aarch64]" >&2; exit 1 ;;
esac
