#!/bin/sh
# gen-embbuild-manifest.sh — emit the EmbBuild manifest that builds EmbCC ON
# EmbLinkOS (ROADMAP M4: "the OS builds the compiler that builds the OS's
# programs"). EmbBuild is a typed-manifest walker (myos docs/BUILD.md): each
# target is `name/kind/inputs/args/output`, each recipe one spawn.
#
# The manifest is GENERATED, not hand-written, on purpose. BUILD.md §6 records
# the format's real cost: a hand-listed `inputs:` header set silently goes
# stale when the include graph grows, and staleness detection then misses an
# edit. So the header closure of every unit is DERIVED here (cc -MM), exactly
# what §6 argues for. Re-run this whenever the sources or their includes change.
#
# Paths are the on-OS layout (docs/SELFHOST_ONOS.md): sources under
# /data/src/embcc (the src/ prefix dropped, subdirs preserved), EmbCC's own
# freestanding headers at /data/apps/embcc/include, newlib's ABI headers at
# /system/abi/include, the ABI objects at /system/abi, outputs staged under
# /data/build/out/embcc (EmbBuild NEVER writes /system — BUILD.md §3).
#
#   usage: tools/gen-embbuild-manifest.sh > build.ebm
#   env:   NEWLIB_INC  host newlib include dir (to compute the closure)
set -eu

cd "$(dirname "$0")/.."
NEWLIB_INC=${NEWLIB_INC:-/home/motsou/cross/newlib-c99/x86_64-elf/include}

# On-OS roots.
SRCROOT=/data/src/embcc
INCEMB=/data/apps/embcc/include
INCABI=/system/abi/include
OUTDIR=/data/build/out/embcc
ABI=/system/abi

# EmbCC's own translation units — the self-host source set (tests/golden/
# self-host.sh). Kept in step with the Makefile's SRCS.
SRCS="src/driver/main.c src/driver/util.c src/lex/lex.c src/parse/parse.c
      src/sema/sema.c src/sema/type.c src/ir/irgen.c src/as/as.c src/opt/opt.c
      src/codegen/codegen.c src/debug/dwarf.c src/asm/emit.c src/asm/topasm.c
      src/cpp/predef.c src/cpp/cpp.c src/elf/write.c"

# Map a host path to its on-OS path.
mappath() {
    case "$1" in
        include/*)        echo "$INCEMB/${1#include/}" ;;
        src/*)            echo "$SRCROOT/${1#src/}" ;;
        "$NEWLIB_INC"/*)  echo "$INCABI/${1#"$NEWLIB_INC"/}" ;;
        *)                echo "$1" ;;
    esac
}

printf '# /data/src/embcc/build.ebm -- EmbBuild builds EmbCC, on the OS (ROADMAP M4).\n'
printf '# GENERATED by tools/gen-embbuild-manifest.sh -- do not hand-edit; header\n'
printf '# closures are derived (BUILD.md 6). The total loop: embcc builds embcc,\n'
printf '# embld links it, all from /data/src on the metal.\n\n'
printf 'project: embcc\n\n'

objs=""
for src in $SRCS; do
    rel=${src#src/}
    obj=$(echo "$rel" | tr / _); obj=${obj%.c}.o

    # Header closure: cc -MM, strip the `target:` and line-continuations, then
    # normalise each dep (resolve `..`) and map to its on-OS path.
    inputs=$(mappath "$src")
    deps=$(cc -MM -Iinclude -I"$NEWLIB_INC" "$src" 2>/dev/null \
           | sed 's/^[^:]*://; s/\\//g')
    for d in $deps; do
        [ "$d" = "$src" ] && continue
        case "$d" in
            /*) : ;;                                    # absolute (newlib): as-is
            *)  d=$(realpath --relative-to="$PWD" "$d" 2>/dev/null || echo "$d") ;;
        esac
        inputs="$inputs $(mappath "$d")"
    done

    # A header pulled through several paths appears once (order preserved).
    inputs=$(printf '%s\n' $inputs | awk '!seen[$0]++' | tr '\n' ' ')
    printf 'name: %s\n' "$obj"
    printf 'kind: compile\n'
    printf 'inputs: %s\n' "$inputs"
    printf 'args: /data/apps/embcc/embcc.elf -c -I%s -I%s %s -o %s/%s\n' \
           "$INCEMB" "$INCABI" "$(mappath "$src")" "$OUTDIR" "$obj"
    printf 'output: %s/%s\n\n' "$OUTDIR" "$obj"
    objs="$objs $OUTDIR/$obj"
done

# The link: crt0 + syscalls + every object + libc, exactly the self-host line
# (tests/golden/self-host.sh), through EmbLD.
printf 'name: embcc.elf\n'
printf 'kind: link\n'
printf 'inputs: %s/crt0.o %s/syscalls.o%s %s/libc.a\n' "$ABI" "$ABI" "$objs" "$ABI"
printf 'args: /data/apps/embld/embld.elf -o %s/embcc.elf %s/crt0.o %s/syscalls.o%s %s/libc.a\n' \
       "$OUTDIR" "$ABI" "$ABI" "$objs" "$ABI"
printf 'output: %s/embcc.elf\n' "$OUTDIR"
